### ISSUE TITLE
[LTM-33] 당첨 정보 상세 회차 선택 피커 View 수정

### ISSUE THREAD

**Issue by w36495** [LottoMate/LottoMate-Android#14]
## 💡 ISSUE
당첨 정보 상세 회차 선택 피커 View 수정

## 🎯 TODO
- [ ] 로또 회차 선택 시, pressed 효과 제거
- [ ] 피커 활성화 시, 배경색 적용
- [ ] 피커 UI 수정
